travis:
  secure:
    BINSTAR_TOKEN: ozX0IVL4IMLlIacbKzNXztPmzDWaZtxsfeB9McIrMp0lzMTev5G3y+v6umvbG+vilSGFaA20WzG4kkiSU5zO766aPSH/U99zcJDhK3ZbL8wn4bwIg3sqhYLY1kgIrcPNBlh2/48+Fqvk+npe2rzGgBAO9iONduOVlg6sIkYzKOdi+hV6e+j0XI2uwORbHB/hS24XWFPUn4YqujqoexxNGKwvrR7eHNvfPSmM4gAZaB+i+LF39Ple8JM41Zl++wQoJ67kwknGnHzWsqY91pLVOwv0ligyNOi+4jv4lSbkFOWMxbN2+emr0kWWwYO3VHfmxA0luOvxaDxTqb9o89SR//dJUoppk2J1oTbJQQn+IcD0Bg5V9U9xUkc7yynZKsNw/mlZmDkPOKQeDs2ynhTwklwZZElBWxqg3pSysd8lYrAA5cCGSM11UlMbHixqXQyGoesc41Y5+cyxBv/In7QS0OdvlVmzou3X7aWjG+FojcP6p4lvE4Qh2b0va4MV6e7OXWO5z9CVOiG6OQfog16u9QUAfOzZH062YpkfYRFm6KL++IRMZfSJux6XCi/lZhF3gc5hn5oGIdbI64NwlPwgv3BF9ZKM4c+rlgDr3QPtN+Rro5oPnn1wBmmOOJq+oepvsEMw8Z7NOXmwdBGUvlVwVCUpZGY8b4leyqv4699CQHE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
