travis:
  secure:
    BINSTAR_TOKEN: xKc7EgoORNuUPVCjOmEe+ds1nEq5eFVgE9j9/5IVhaL1k5PF605+csXZZeXL7uoBQfHD2Je3mJrScPDsTMsy5ftH8bHcFlQxTudiC7G2Df0f9GjNbpCa0J9ko0x5i94rRnbJWInCqmmEuKcXYVcm5S5ObcRDVswUd14JLQiiACb+eLTTWerJHoZntbffMrVjOkFdCMgVJdrGnawVh0XG+krD+Ye+oZeOOKYXAc+OJMgfPVvP2FTKRKzko+/PoqtrcwVQDuQaFAwRrRPiuN+ezTZd8gcmHZb1ubkcuzIj2UQWDLdB9CxlxoVab4n+iio/Wy3PzS19nWt460rAiwgMCo+XB5b2rVDnJpF1zUpQtH6QCUxsJTc0lQXxUBHaa62uEcZ+IgCIXmSNzRMFF67FtizW2zMzUBir0FiQijSwM9nDgHMWXfLkZ5PcaoVkmEZ1TUqB9sCOK/ROkoWOmUzQmh76dklW4wL8zEpsGHn3vwKKzfMoem6lPf7MwLlBu4x++YlxOjMcc/QEuzxwSwlTfwwFeZ98ylejZTqwME72yBospevg5/AIQnBICfjvSA8cR1dQbqlfuAgdf3qH5BnBc9vtWDUq5Bopv+2NhakWqHO6Zv3DLJ/4haqrnnK+USgW7d7DYJm3yCWEOFh5EaJZjCheD+3nKuvkd1+LsJ7TRbI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
