travis:
  secure:
    BINSTAR_TOKEN: hW1Y2Fv3UFEzSwzNPOJ1294rKd2I1g1xoWNGSgODR9zL8qUQdxcgJgQnPWHFNeJjZxEfUkMxAxLr1mDwLwOA/652gvGwBFb+hU36IoJNX+20pRY+or1CcNJBEc0KEHaXc/xAYC1Xin0oFdQmvifiaXv/5IyAlXXtxcCpnXv4/73XmmdP5c+7jRw14PNKb1j7v+sH7+6t+j81JTQdqBj5AfCgre4aXTbDpy7+Eq/QJ27IADziN6SoFHZ+lJ1135oar8/4k8Ug5kpxmlPuqWDE+vLMWVDjlookxOKakFK+luOkTQfosKl/qjMHj9Jvuljoe2gfGmmyW8RqQXuHmbihhG7+9sslEIWo/hL+98F8AX0t4iK6nszYo6uxetGHaNEncdfSTHevRDMWTYqL3ZGac9KSJ7aryMGKiGDOfHCcVWVtVtcwC/s2N/ejMrHK2pL6fkoPT9nYQ22O+6HHNkykr61F2QmyMBzRpBU9kuBmVuzDi4Pix/CPA5o4KrIetpOJB1qgt1DORemUFp/wYK3fHr7Rt/qmIHKKenU9z45/hOGGV1Z7mIiEOqlNbmQx0fW9Bw2kG5dwLy+OCs+eYLF3LWmQrUfARHDM18tfc1cCRhCcxY0C8ncWRWOspWjjWAg9uHhs4y89Ej6vnRUBRLpMkkBECaQerqR4tJsv26da8+w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
