travis:
  secure:
    BINSTAR_TOKEN: zVbbo2TcaxwXPy2vChB6wDU5V2m+PokdKyHaMMEB9ImII/NoLPzwYn5VWcNwzx+JxwCLLdn5ZZuRCZ7c9LwScRBSMtsGRRwG6fHkYZyl6jFb+kfDY4Jqvgd3GybV4nseaza59mlEQcGv6jn1tdBMHTYUqKRNpmvS58e5QlqDA78fgUxb8T/IhmbHd9RMo7EDIQxtl3/T8kZUALGfvssHbfqrKrpxzLRvAn55p2TWHQaWiv8FJjzyW1X3MVjytXFWG6AiGDjTDm8UlYpv3X+ZShp53ANyyMy7607uT9zD/M8CafbR4oLRQbdvGEMMt8rRL4uKngdrxRL+q6p/exmZiJlnID1ZJYkUA51++17vn4e1YnVFRY6lIfXYDGEqU9/yiiPfiA4YWqXkAY4BzOlVTXsd4e1Fe43RPDsJuh0AdrBp9VUtX2N3JMttJSYekcOb4+6J/P9WYnBDqWkejW6CEomQbW7X1hz2s7d5esLG8B2K7YlXZd3solfF2FhkYMFL63AaJjtS7+EKFkaat8wMmtD3ZDECF4QVknaJQRoQmKleVnXktE2BStNEiBfevN9B81ucZ1OE5rdByUYN1IRwdqKZ+3RetkC9hwNqbOZ+JyYeecYvcn4jEU3l2ytNB+ALvuf0OrNs0UFsvEBghsorKKlmSKzsyNkBgqjiAq8BDIw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
